### ISSUE TITLE
[FEAT] :sparkles: Implement unit tests

### ISSUE THREAD

**Issue by tenshiAMD** [shriproperty/repository-commander#39]
### Description

Nice project! Unit tests are a must-have for bots. We do not want bots going rogue, right?

**Comment by aayushchugh** [comment]
I will add these today thanks for the feedback

**Comment by aayushchugh** [comment]
@tenshiAMD Just figured out that there are no benefits of unit test in probot because they will pass in all the cases
because we can't test them with actual GitHub Api

**Comment by tenshiAMD** [comment]
@aayushchugh Ok sure. I just don't feel like using any apps, especially bots that are not properly tested. Other probot-based apps and bots I'm using have done some tests.

**Comment by aayushchugh** [comment]
@tenshiAMD try testing them locally they all will pass even where they need to be filling

**Comment by tenshiAMD** [comment]
> @tenshiAMD try testing them locally they all will pass even where they need to be failing

@aayushchugh then if that means those parts can be buggy for the bots when you expect it to fail but it succeeds instead.

**Comment by aayushchugh** [comment]
@tenshiAMD Yeah they will succeed even if they should be failing because when I check probot docs they disabled to make call to actual GitHub api so they will just succeed because they are not testing it against GitHub api

**Comment by tenshiAMD** [comment]
> @tenshiAMD Yeah they will succeed even if they should be failing because when I check probot docs they disabled to make call to actual GitHub api so they will just succeed because they are not testing it against GitHub api

@aayushchugh that's weird they should somehow allow mock tests or something. Try to check other probot-based apps and bots.

**Comment by aayushchugh** [comment]
@tenshiAMD I took reference from many of them they all just disabled the github api
